# 1 Native Data Types

## 1.1 Float, complex, integer, boolean, strings

In [25]:
# Enter float number
x=float(1)
print(type(x)) # show data type

# complex number
x=2+3j
x=complex(2,3)
print("complex number x=",x)

# power index
x=2**3
print("3rd power of 2=",x)

# boolean
x=True
x=bool(1)
print("x=",x)
x=bool()
print("x=",x)

# string
x='apple'
y=x[:]
print("entire string=",y)
y=x[0]
print("first char=",y)
y=x[2:]
print("char from the 3rd place=",y)
y=x[:2]
print("char before the 3rd place=",y)
y=x[1:3]
print("char from the 2nd place and before the 4th place=",y)
y=x[0:5:2]
print("char with a step of 2=",y)
y=x[-1]
print("char at the last 2nd place=",y)

<class 'float'>
complex number x= (2+3j)
3rd power of 2= 8
x= True
x= False
entire string= apple
first char= a
char from the 3rd place= ple
char before the 3rd place= ap
char from the 2nd place and before the 4th place= pp
char with a step of 2= ape
char at the last 2nd place= e


## 1.2 Lists

In [52]:
x=[0,1,2,3,4,5,6,7,8,9]
a=[10,20,30]
print("length of array=",len(x))
x.append(10)
print("append a number=",x)
x.extend(a)
print("append an array=",x)
x.pop(0)
print("remove an element from an array=",x)
x.remove(5)
print("remove the 1st occurence of a value from an array=",x)
print("numbers of a value in an array=",x.count(10))
del x[:3]
print(x)

length of array= 10
append a number= [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
append an array= [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 10, 20, 30]
remove an element from an array= [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 10, 20, 30]
remove the 1st occurence of a value from an array= [1, 2, 3, 4, 6, 7, 8, 9, 10, 10, 20, 30]
numbers of a value in an array= 2
[4, 6, 7, 8, 9, 10, 10, 20, 30]


Lists are mutable and changes to copy also affect the original list. Use copy method and slicing to prevent the passing.

In [192]:
x=[1,2,3]

y=x
y[0]=4
print("x=",x)
print("x_id=",id(x))
print("y_id=",id(y))

y=x[:]
print("x_id=",id(x))
print("y_id=",id(y))

print("x_id_element=",id(x[0]))
print("y_id_element=",id(y[0]))

import copy as cp
y=x
z=cp.deepcopy(x)
print("x_id=",id(x))
print("y_id=",id(y))
print("z_id=",id(z))

x= [4, 2, 3]
x_id= 4463830408
y_id= 4463830408
x_id= 4463830408
y_id= 4463831624
x_id_element= 4305308256
y_id_element= 4305308256
x_id= 4463830408
y_id= 4463830408
z_id= 4464010696


## 1.3 Tuples 

In [54]:
x=(0,1,2,3,4,5,6,7,8,9)
print (x[-10:-5])
y=list(x)
z=tuple(y)

(0, 1, 2, 3, 4)


## 1.4 Dicitonaries

Dictionaries are composed of keys and values.  Keys must be unique and immutable.

In [98]:
data={'age':34,'children':[1,2],'fruit':'apple'}
data['name']='abc'  #add a K-V pair
del data['age']     #delete a keyword
print(data)

from collections import OrderedDict
od=OrderedDict()
od['A']=1
od['B']='alpha'
print(list(od.keys()))

from collections import defaultdict
od=defaultdict(list)
od['B'].append('beta')
print(od)

{'children': [1, 2], 'fruit': 'apple', 'name': 'abc'}
['A', 'B']
defaultdict(<class 'list'>, {'B': ['beta']})


## 1.5 Sets

In [80]:
x=set(['a','b','c','d','e'])
y=set(['a','b','x','y'])
x.add('f')
print("add an element to set=",x)
x.remove('d')
a=x.intersection(y)
print("intersection of two sets=",a)
a=x.union(y)
print("union of two sets=",a)

add an element to set= {'a', 'c', 'd', 'e', 'f', 'b'}
intersection of two sets= {'a', 'b'}
union of two sets= {'a', 'c', 'y', 'e', 'f', 'x', 'b'}


## 1.6 Ranges

In [82]:
x=range(3,10)
print(list(x))
x=range(3,10,3)
print(list(x))

[3, 4, 5, 6, 7, 8, 9]
[3, 6, 9]


## 1.7 Arrays

In [199]:
from numpy import *
#import numpy
x=array([[0.,1,2,3,4],[5,6,7,8,9]])
print("Array_dimension_value=",shape(x))
print("Array_dimension=",x.ndim)
print("Data Type=",x.dtype)
x=array([[0.,1,2,3,4],[5,6,7,8,9]],dtype='int32')

x=array([[1,2],[3,4]])
y=array([[5,6],[7,8]])
z=concatenate((x,y),axis=0)
print("concatenate in vertical:",z)
z=concatenate((x,y),axis=1)
print("concatenate in horizontal:",z)
z=vstack((x,y))
print("concatenate in vertical:",z)
z=hstack((x,y))
print("concatenate in horizontal:",z)

x=array([[1]*3]*3)
print("repitious matrix=",x)

x=reshape(arange(9),(3,3))
print("reshape array matrix=",x)
print("flat element=",x.flat[5])

Array_dimension_value= (2, 5)
Array_dimension= 2
Data Type= float64
concatenate in vertical: [[1 2]
 [3 4]
 [5 6]
 [7 8]]
concatenate in horizontal: [[1 2 5 6]
 [3 4 7 8]]
concatenate in vertical: [[1 2]
 [3 4]
 [5 6]
 [7 8]]
concatenate in horizontal: [[1 2 5 6]
 [3 4 7 8]]
repitious matrix= [[1 1 1]
 [1 1 1]
 [1 1 1]]
reshape array matrix= [[0 1 2]
 [3 4 5]
 [6 7 8]]
flat element= 5


Slice of an array will affect the original array. To avoid passing, use the following methods.

In [187]:
x=reshape(arange(4),(2,2))
s1=copy(x[0,:])
s2=x[0,:].copy()
s3=array(x[0,:])

## 1.8 Matrix

In [194]:
import numpy as np
x=np.asmatrix([1,2,3])
y=np.matrix([1,2,3])