# 2 Math and Functions

# 2.1 Broadcasting

In [127]:
from numpy import *
x=array([1,2,3])
y=array([[1],[1],[1]])
print("x+y=",x+y)

x=array([[1,2,3,4]])
y=reshape(x,(4,1))
b1=broadcast(x,y) #quicker
b2=broadcast_arrays(x,y) 

x+y= [[2 3 4]
 [2 3 4]
 [2 3 4]]


# 2.2 Multiplication

In [20]:
from numpy import *
x=array([[0,1],[2,3],[4,5]])
y=array([[1,2],[3,4]])
print("Product=",x@y)  #this method supports broadcasting
print('Product also=',x.dot(y))

Product= [[ 3  4]
 [11 16]
 [19 28]]
Product also= [[ 3  4]
 [11 16]
 [19 28]]


# 2.3 Transpose

In [25]:
from numpy import *
x=asmatrix([[1,2],[3,4]])
print(x.transpose())

[[1 3]
 [2 4]]


## 2.4 Generating

In [95]:
from numpy import *
x=linspace(0,10,11) #11 points uniformly between 0 and 10
x=logspace(0,10,11) #identical to 10**linspace(0,10,11)
x=r_[0:1:0.1]
x=c_[0:10:15j]

x=reshape(arange(9),(3,3))
print("use ix method to slice=",x[ix_([1,2],[0])])

x=arange(0,1,0.1)
y=arange(0,1,0.2)
a,b=meshgrid(x,y)
a,b=mgrid[0:1:3j,0:2:5j]
a,b=ogrid[0:1:3j,0:2:5j]

x,y=3,2
print('all-1 matrix=',ones((x,y)))
print('all-0 matrix=',zeros((x,y)))
print('all-empty matrix=',empty((x,y)))
print('diag-1 matrix=',eye((x)))
print('diag-1 matrix also=',identity((x)))

x=array([[0,1],[2,3]])
print('tile of x=',tile(x,(2,3)))

use ix method to slice= [[3]
 [6]]
all-1 matrix= [[ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]]
all-0 matrix= [[ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]]
all-empty matrix= [[ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]]
diag-1 matrix= [[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
diag-1 matrix also= [[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
tile of x= [[0 1 0 1 0 1]
 [2 3 2 3 2 3]
 [0 1 0 1 0 1]
 [2 3 2 3 2 3]]


## 2.5 Math

In [46]:
#Sum
from numpy import *
x=array([[1,2,3],[4,5,6]])
print('sum of all elements=',sum(x))
print('sum of rows=',sum(x,0))
print('sum of cols=',sum(x,1))
print('cumsum of rows',cumsum(x,0))

sum of all elements= 21
sum of rows= [5 7 9]
sum of cols= [ 6 15]
cumsum of rows [[1 2 3]
 [5 7 9]]


If there is a nan, use nansum function.  Similarly we have nanmax, nanargmax.  
prod and cuprod behave similarly to sum and cumsum.  
Other math functions: diff(), exp(), log(), log10(), sqrt(), square(), abs(), sign(), real(), imag(), conj(), unique().

In [56]:
from numpy import *

#compare whether x elements are in y
x=arange(10)
y=arange(5,15)
print('Whether x element is in y=',in1d(x,y))

#intersection of elements in both x and y
print('intersection=',intersect1d(x,y))

#union of elements in x and y
print('union=',union1d(x,y))
print('setxor=',setxor1d(x,y))

#elements in x but not in y
print('setdiff=',setdiff1d(x,y))

Whether x element is in y= [False False False False False  True  True  True  True  True]
intersection= [5 6 7 8 9]
union= [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
setxor= [ 0  1  2  3  4 10 11 12 13 14]
setdiff= [0 1 2 3 4]


In [71]:
#Sort
x=array([[2,3],[1,0],[5,4]])
print('sort by row=',sort(x))
print('sort by col=',sort(x,0))
print('sort as flat=',sort(x,axis=None))

sort by row= [[2 3]
 [0 1]
 [4 5]]
sort by col= [[1 0]
 [2 3]
 [5 4]]
sort as flat= [0 1 2 3 4 5]


In [79]:
#Max and Min
x=array([[2,3],[1,0],[5,4]])
print('max of all=',amax(x))
print('max of row=',amax(x,0))
print('max of col=',amax(x,1))

from numpy.random import *
x=randn(3)
y=randn(3)
print('max of x and y=',maximum(x,y))

max of all= 5
max of row= [5 4]
max of col= [3 1 5]
max of x and y= [ 2.11273354  0.34378038  0.25819324]


In [103]:
#View
x=arange(3)
x.view(matrix)
x=array([[1,2],[3,4]])
print(x.ravel())
print(x.flatten()) #works like ravel but copies the array
print(x.flat[:])# an interator of a matrix

[1 2 3 4]
[1 2 3 4]
[1 2 3 4]


In [130]:
# Split
x=reshape(arange(20),(4,5))
y=vsplit(x,[1,2])
y=hsplit(x,[1,3])

In [134]:
#Delete
x=reshape(arange(20),(4,5))
y=delete(x,1,0)       #delete row1
y=delete(x,[2,3],1)   #delete col2,3

[[ 0  1  4]
 [ 5  6  9]
 [10 11 14]
 [15 16 19]]


In [141]:
#Flip
x=reshape(arange(1,5),(2,2))
print('Left-right conversion=',fliplr(x))
print('Up-down conversion=',flipud(x))

Left-right conversion= [[2 1]
 [4 3]]
Up-down conversion= [[3 4]
 [1 2]]


In [143]:
# Linear Algebra
x=reshape(arange(1,5),(2,2))
print("diag=",diag(x))
print("triangle-up=",triu(x))
print("triangle-lower=",tril(x))

#solve linear equation
from numpy.linalg import solve
x=array([[1,2,3],[3,3,4],[1,1,4]])
y=array([[1],[2],[3]])
print('solution is:',solve(x,y))

diag= [1 4]
triangle-up= [[1 2]
 [0 4]]
triangle-lower= [[1 0]
 [3 4]]
solution is: [[ 0.625]
 [-1.125]
 [ 0.875]]


When the number of columns is smaller than the number of rows, lstsq method will find the least squares solution.